### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by fceschmidt** [andycloke/verb-master#1]
Hi Andy, just a short observation, I tried your program and gave the following input:

Tense: Imperative (Affirmative)
Verb: hacer - to do
Ella [haga]

The page corrected me and said that it should have been "ella haced" - but I was right according to [this site](http://www.conjugacion.es/del/verbo/hacer.php).

Cheers!

**Comment by fceschmidt** [comment]
The same happens for Ella, descansar, Imperative (Affirmative). Apparently the problem applies especially to this tense and person.

**Comment by andycloke** [comment]
Will look into, thanks guys!

**Comment by andycloke** [comment]
Appears to be an error in the CSV file of the verb database I used. Looking into using the XLS file instead.

**Comment by andycloke** [comment]
all fixed. had to switch the data to the XLS. bonus is that the XLS has all the common/ irreg / reflexive verbs flagged, so i can add that as aa feature.
